-- Hephaestus initial schema.
--
-- Conventions:
-- * Primary keys are UUIDv7 generated by the application (time-ordered).
-- * Enumerated values are TEXT + CHECK constraints: altering a CHECK is
--   a normal backward-compatible migration; PostgreSQL native enums are
--   not (see ADR-009).
-- * Every organization-scoped table carries organization_id so tenant
--   scoping can be enforced (and tested) on every query.
-- * Timestamps are TIMESTAMPTZ in UTC always.

CREATE TABLE organizations (
    id          UUID PRIMARY KEY,
    name        TEXT NOT NULL,
    slug        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT organizations_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$')
);

CREATE UNIQUE INDEX organizations_slug_uidx ON organizations (slug);

CREATE TABLE projects (
    id                UUID PRIMARY KEY,
    organization_id   UUID NOT NULL REFERENCES organizations(id),
    name              TEXT NOT NULL,
    slug              TEXT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT projects_slug_format CHECK (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$')
);

CREATE UNIQUE INDEX projects_org_slug_uidx ON projects (organization_id, slug);

CREATE TABLE repositories (
    id               UUID PRIMARY KEY,
    organization_id  UUID NOT NULL REFERENCES organizations(id),
    project_id       UUID NOT NULL REFERENCES projects(id),
    remote_url       TEXT NOT NULL,
    default_branch   TEXT NOT NULL DEFAULT 'main',
    display_name     TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX repositories_org_idx ON repositories (organization_id);
CREATE INDEX repositories_project_idx ON repositories (project_id);

CREATE TABLE tasks (
    id                UUID PRIMARY KEY,
    organization_id   UUID NOT NULL REFERENCES organizations(id),
    project_id        UUID NOT NULL REFERENCES projects(id),
    repository_id     UUID NOT NULL REFERENCES repositories(id),
    title             TEXT NOT NULL,
    description       TEXT NOT NULL DEFAULT '',
    priority          TEXT NOT NULL DEFAULT 'medium',
    risk              TEXT NOT NULL DEFAULT 'medium',
    labels            JSONB NOT NULL DEFAULT '[]'::jsonb,
    idempotency_key   TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT tasks_priority_ck CHECK (priority IN ('critical','high','medium','low')),
    CONSTRAINT tasks_risk_ck CHECK (risk IN ('low','medium','high','critical')),
    CONSTRAINT tasks_title_len_ck CHECK (char_length(title) BETWEEN 1 AND 512)
);

-- Idempotent task creation: same key within an org returns the same row.
CREATE UNIQUE INDEX tasks_idem_uidx ON tasks (organization_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX tasks_org_created_idx ON tasks (organization_id, created_at DESC);
CREATE INDEX tasks_project_idx ON tasks (project_id);

CREATE TABLE requirements (
    id           UUID PRIMARY KEY,
    task_id      UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    category     TEXT NOT NULL,
    kind         TEXT NOT NULL,
    statement    TEXT NOT NULL,
    source       TEXT NOT NULL DEFAULT '',
    gating       BOOLEAN NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT requirements_category_ck CHECK (category IN
        ('functional','non_functional','security','performance','compatibility','constraint')),
    CONSTRAINT requirements_kind_ck CHECK (kind IN ('explicit','inferred','assumption','unknown')),
    CONSTRAINT requirements_stmt_len_ck CHECK (char_length(statement) BETWEEN 1 AND 8192)
);

CREATE INDEX requirements_task_idx ON requirements (task_id);

CREATE TABLE plans (
    id             UUID PRIMARY KEY,
    task_id        UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    objective      TEXT NOT NULL,
    affected_components JSONB NOT NULL DEFAULT '[]'::jsonb,
    affected_symbols    JSONB NOT NULL DEFAULT '[]'::jsonb,
    strategy       JSONB NOT NULL DEFAULT '{}'::jsonb,
    prompt_version TEXT,
    superseded_by  UUID REFERENCES plans(id),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT plans_objective_len_ck CHECK (char_length(objective) BETWEEN 1 AND 8192)
);

CREATE INDEX plans_task_idx ON plans (task_id);

CREATE TABLE plan_steps (
    id            UUID PRIMARY KEY,
    plan_id       UUID NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
    position      INT  NOT NULL,
    action        TEXT NOT NULL,
    verification  TEXT NOT NULL,
    risks         JSONB NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT plan_steps_pos_ck CHECK (position >= 1),
    CONSTRAINT plan_steps_action_len_ck CHECK (char_length(action) BETWEEN 1 AND 8192),
    CONSTRAINT plan_steps_verif_len_ck CHECK (char_length(verification) BETWEEN 1 AND 8192)
);

CREATE INDEX plan_steps_plan_idx ON plan_steps (plan_id, position);

-- Durable workflow runs. state changes ONLY through legal transitions
-- enforced by hephaestus-core and re-checked here via expected-state CAS.
CREATE TABLE workflow_runs (
    id                  UUID PRIMARY KEY,
    task_id             UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    organization_id     UUID NOT NULL REFERENCES organizations(id),
    state               TEXT NOT NULL DEFAULT 'created',
    attempt             INT  NOT NULL DEFAULT 1,
    correlation_id      UUID NOT NULL,
    lease_owner         TEXT,
    lease_expires_at    TIMESTAMPTZ,
    last_transition_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT workflow_runs_state_ck CHECK (state IN
        ('created','analyzing','planning','awaiting_approval','implementing',
         'verifying','reviewing','awaiting_merge','building','deploying',
         'verifying_deployment','completed','failed','cancelled')),
    CONSTRAINT workflow_runs_attempt_ck CHECK (attempt >= 1)
);

CREATE INDEX workflow_runs_task_idx ON workflow_runs (task_id);
CREATE INDEX workflow_runs_lease_idx ON workflow_runs (state, lease_expires_at)
    WHERE lease_owner IS NOT NULL;

-- Append-only event log.
CREATE TABLE events (
    id               UUID PRIMARY KEY,
    schema_version   INT  NOT NULL,
    organization_id  UUID NOT NULL,
    aggregate        TEXT NOT NULL,
    aggregate_id     UUID NOT NULL,
    correlation_id   UUID NOT NULL,
    provenance       TEXT NOT NULL,
    payload          JSONB NOT NULL,
    occurred_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT events_aggregate_ck CHECK (aggregate IN
        ('organization','project','repository','task','workflow_run',
         'execution','agent_run','build','deployment','artifact')),
    CONSTRAINT events_provenance_ck CHECK (provenance IN
        ('system','user','task_input','repository_data','tool_result','model_output','computed'))
);

CREATE INDEX events_aggregate_idx ON events (aggregate, aggregate_id, occurred_at);
CREATE INDEX events_correlation_idx ON events (correlation_id);
CREATE INDEX events_org_time_idx ON events (organization_id, occurred_at DESC);

-- Durable job queue with leases and dead-letter semantics.
CREATE TABLE jobs (
    id               UUID PRIMARY KEY,
    queue            TEXT NOT NULL DEFAULT 'default',
    priority         INT  NOT NULL DEFAULT 0,
    payload          JSONB NOT NULL,
    status           TEXT NOT NULL DEFAULT 'pending',
    run_after        TIMESTAMPTZ NOT NULL DEFAULT now(),
    attempts         INT  NOT NULL DEFAULT 0,
    max_attempts     INT  NOT NULL DEFAULT 5,
    lease_owner      TEXT,
    lease_expires_at TIMESTAMPTZ,
    last_error       TEXT,
    idempotency_key  TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT jobs_status_ck CHECK (status IN ('pending','running','done','failed','dead')),
    CONSTRAINT jobs_priority_ck CHECK (priority BETWEEN -100 AND 100),
    CONSTRAINT jobs_attempts_ck CHECK (attempts >= 0 AND max_attempts >= 1)
);

-- Claim path: newest-ready highest-priority job, skipping locked rows.
CREATE INDEX jobs_claim_idx ON jobs (queue, status, priority DESC, run_after)
    WHERE status IN ('pending');
-- Recovery path: find leases that expired while worker died.
CREATE INDEX jobs_lease_expiry_idx ON jobs (status, lease_expires_at)
    WHERE status = 'running';
CREATE UNIQUE INDEX jobs_idem_uidx ON jobs (queue, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- Approval gates: policy decides which require human decisions.
CREATE TABLE approvals (
    id            UUID PRIMARY KEY,
    task_id       UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    run_id        UUID REFERENCES workflow_runs(id),
    gate          TEXT NOT NULL,
    required_role TEXT NOT NULL,
    decision      TEXT,
    decided_by    TEXT,
    decided_at    TIMESTAMPTZ,
    reason        TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT approvals_gate_ck CHECK (gate IN ('plan','merge','deploy_staging','deploy_production','migration','policy_change','credential_change')),
    CONSTRAINT approvals_decision_ck CHECK (decision IS NULL OR decision IN ('approved','rejected'))
);

CREATE INDEX approvals_task_idx ON approvals (task_id);
CREATE INDEX approvals_open_idx ON approvals (run_id) WHERE decision IS NULL;

-- Tamper-evident audit log. Hash chaining gives practical tamper
-- detection: each entry commits to the previous entry's hash.
CREATE TABLE audit_log (
    id          BIGSERIAL PRIMARY KEY,
    prev_hash   TEXT NOT NULL DEFAULT '',
    hash        TEXT NOT NULL,
    actor       TEXT NOT NULL,
    action      TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id   TEXT,
    detail      JSONB NOT NULL DEFAULT '{}'::jsonb,
    at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_actor_idx ON audit_log (actor, at DESC);
CREATE INDEX audit_target_idx ON audit_log (target_type, target_id);
