//! Versioned internal event model.
//!
//! Everything meaningful that happens in Hephaestus emits an event with:
//! * a stable schema version,
//! * provenance classification (see Provenance),
//! * correlation identifiers for tracing across subsystems.
//!
//! Events are append-only records; consumers must treat them as facts.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::id::{HephaestusId, OrganizationId};

/// Current envelope version. Bump on incompatible wire changes.
///
/// v2 adds the execution-phase payloads (plan decisions, executions,
/// steps, verifications, reviews). v1 envelopes stay readable; the new
/// variants simply never appear in them.
pub const EVENT_ENVELOPE_VERSION: u32 = 2;

/// Where a piece of content originated.
///
/// Provenance is central to prompt-injection defense: content from
/// untrusted sources must never be interpreted as instructions by
/// agents; enforcement happens outside the model (policy engine).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Provenance {
    /// Generated by Hephaestus itself.
    System,
    /// Originated from a human user.
    User,
    /// Declared task input (title/description/requirements).
    TaskInput,
    /// Content read from a repository (source files, issues, docs).
    RepositoryData,
    /// Output of a tool invocation.
    ToolResult,
    /// Output of a model provider call.
    ModelOutput,
    /// Derived by a deterministic Hephaestus computation.
    Computed,
}

/// Aggregate kinds events can attach to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AggregateKind {
    /// An organization.
    Organization,
    /// A project.
    Project,
    /// A repository connection.
    Repository,
    /// A task.
    Task,
    /// A workflow run.
    WorkflowRun,
    /// An execution attempt.
    Execution,
    /// An agent run.
    AgentRun,
    /// A build.
    Build,
    /// A deployment.
    Deployment,
    /// An artifact.
    Artifact,
}

/// Typed event payloads. Adding or reshaping a variant requires a
/// schema-version bump per the compatibility policy (see docs/adr).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "type", content = "data")]
pub enum EventPayload {
    /// A task was created.
    TaskCreated {
        /// The new task.
        task_id: HephaestusId,
    },
    /// Requirements were extracted for a task.
    RequirementsExtracted {
        /// Owning task.
        task_id: HephaestusId,
        /// Number of structured requirements produced.
        count: u32,
    },
    /// A plan was generated.
    PlanGenerated {
        /// Owning task.
        task_id: HephaestusId,
        /// The plan.
        plan_id: HephaestusId,
    },
    /// An execution attempt started over an approved plan.
    ExecutionStarted {
        /// The execution.
        execution_id: HephaestusId,
        /// The plan being executed.
        plan_id: HephaestusId,
    },
    /// One plan step reached a terminal outcome inside an execution.
    StepExecuted {
        /// Owning execution.
        execution_id: HephaestusId,
        /// The executed step.
        step_id: HephaestusId,
        /// Outcome: "completed" or "failed".
        outcome: String,
    },
    /// A workflow run changed state.
    WorkflowStateChanged {
        /// The run.
        run_id: HephaestusId,
        /// Previous state name.
        from: String,
        /// Next state name.
        to: String,
        /// Which trigger caused it.
        trigger: String,
    },
    /// A tool was invoked (audit record reference).
    ToolInvoked {
        /// Invocation id.
        invocation_id: HephaestusId,
        /// Tool name.
        tool: String,
        /// Whether authorization allowed it.
        authorized: bool,
    },
    /// A file inside a workspace changed during execution.
    FileChanged {
        /// Owning execution.
        execution_id: HephaestusId,
        /// Workspace-relative path (never absolute).
        path: String,
    },
    /// Tests were executed.
    TestRunCompleted {
        /// Verification record.
        verification_id: HephaestusId,
        /// Passed test count.
        passed: u32,
        /// Failed test count.
        failed: u32,
    },
    /// A deterministic verification suite finished for an execution.
    VerificationCompleted {
        /// Owning execution.
        execution_id: HephaestusId,
        /// The verification record.
        verification_id: HephaestusId,
        /// Whether every required layer passed.
        passed: bool,
    },
    /// An automated review produced a verdict for an execution.
    ReviewCompleted {
        /// Owning execution.
        execution_id: HephaestusId,
        /// "approved" or "request_changes".
        decision: String,
        /// Blocking findings when changes were requested.
        blocking: Vec<String>,
    },
    /// Build finished.
    BuildCompleted {
        /// Build id.
        build_id: HephaestusId,
        /// Success flag.
        ok: bool,
        /// Content hash of primary artifact, when built.
        artifact_sha256: Option<String>,
    },
    /// An approval decision was recorded.
    ApprovalDecided {
        /// Approval id.
        approval_id: HephaestusId,
        /// Approved or rejected.
        approved: bool,
        /// Who decided (principal id/display name).
        principal: String,
    },
    /// A deployment reached a terminal verification outcome.
    DeploymentOutcome {
        /// Deployment id.
        deployment_id: HephaestusId,
        /// Verified successfully?
        verified: bool,
        /// Target environment name.
        environment: String,
    },
}

/// Append-only event envelope.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventEnvelope {
    /// Unique event id.
    pub id: HephaestusId,
    /// Envelope schema version.
    pub schema_version: u32,
    /// When the event occurred.
    pub occurred_at: DateTime<Utc>,
    /// Tenant scope.
    pub organization_id: OrganizationId,
    /// Aggregate this event belongs to.
    pub aggregate: AggregateKind,
    /// Aggregate instance id.
    pub aggregate_id: HephaestusId,
    /// Correlation id shared by all events of one logical operation.
    pub correlation_id: Uuid,
    /// Provenance classification.
    pub provenance: Provenance,
    /// Payload.
    pub payload: EventPayload,
}

impl EventEnvelope {
    /// Create a new envelope stamped now.
    pub fn new(
        organization_id: OrganizationId,
        aggregate: AggregateKind,
        aggregate_id: HephaestusId,
        correlation_id: Uuid,
        provenance: Provenance,
        payload: EventPayload,
    ) -> Self {
        Self {
            id: HephaestusId::generate(),
            schema_version: EVENT_ENVELOPE_VERSION,
            occurred_at: Utc::now(),
            organization_id,
            aggregate,
            aggregate_id,
            correlation_id,
            provenance,
            payload,
        }
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;

    #[test]
    fn envelope_round_trips_with_schema_version() {
        let env = EventEnvelope::new(
            OrganizationId::generate(),
            AggregateKind::Task,
            HephaestusId::generate(),
            Uuid::now_v7(),
            Provenance::TaskInput,
            EventPayload::TaskCreated {
                task_id: HephaestusId::generate(),
            },
        );
        let json = serde_json::to_string(&env).expect("serialize envelope");
        let back: EventEnvelope =
            serde_json::from_str(&json).expect("envelope json must round-trip");
        assert_eq!(back.schema_version, EVENT_ENVELOPE_VERSION);
        assert_eq!(back.payload, env.payload);
    }

    #[test]
    fn provenance_is_explicit_on_wire() {
        let env = EventEnvelope::new(
            OrganizationId::generate(),
            AggregateKind::Execution,
            HephaestusId::generate(),
            Uuid::now_v7(),
            Provenance::ModelOutput,
            EventPayload::ToolInvoked {
                invocation_id: HephaestusId::generate(),
                tool: "shell".into(),
                authorized: false,
            },
        );
        let v = serde_json::to_value(&env).expect("to value");
        assert_eq!(
            v.get("provenance").and_then(|p| p.as_str()),
            Some("model_output")
        );
    }
}
